import { Table, Relationship, Column, DataType } from './types';

// Mapa de tipos internos a tipos de Prisma
const PRISMA_TYPE_MAP: Record<DataType, string> = {
    'INT': 'Int',
    'BIGINT': 'BigInt',
    'FLOAT': 'Float',
    'DECIMAL': 'Decimal',
    'BOOLEAN': 'Boolean',
    'VARCHAR': 'String',
    'TEXT': 'String', // @db.Text
    'DATE': 'DateTime', // @db.Date
    'DATETIME': 'DateTime',
    'TIMESTAMP': 'DateTime',
    'JSON': 'Json',
    'UUID': 'String', // @db.Uuid o nativo
    'ENUM': 'Enum', // Requiere manejo especial
};

export class PrismaGenerator {
    private tables: Table[];
    private relationships: Relationship[];

    constructor(tables: Table[], relationships: Relationship[]) {
        this.tables = tables;
        this.relationships = relationships;
    }

    public generate(): string {
        const models = this.tables.map(table => this.generateModel(table)).join('\n\n');
        return `// This file is automatically generated by Project Herman
// Do not edit manually if you plan to regenerate

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

${models}
`;
    }

    private generateModel(table: Table): string {
        const fields = table.columns.map(col => this.generateField(col, table)).join('\n  ');
        const relations = this.generateRelations(table);
        const standardFields = this.generateStandardFields(table);

        return `model ${table.name} {
  ${fields}
  ${relations}
  ${standardFields}
}`;
    }

    private generateField(col: Column, table: Table): string {
        let type = PRISMA_TYPE_MAP[col.type] || 'String';
        let attributes = [];

        // Modificadores de tipo
        if (col.type === 'VARCHAR' && col.options?.length) {
            attributes.push(`@db.VarChar(${col.options.length})`);
        }
        if (col.type === 'TEXT') {
            attributes.push('@db.Text');
        }
        if (col.type === 'DECIMAL') {
            if (col.options?.precision && col.options?.scale) {
                attributes.push(`@db.Decimal(${col.options.precision}, ${col.options.scale})`);
            }
        }

        // Constraints
        if (col.constraints.isPk) {
            attributes.push('@id');
            if (col.type === 'INT' && col.options?.autoIncrement) {
                attributes.push('@default(autoincrement())');
            } else if (col.type === 'UUID') {
                attributes.push('@default(uuid())');
            }
        } else {
            if (col.constraints.isNullable) {
                type += '?';
            }
        }

        if (col.constraints.isUnique) attributes.push('@unique');

        // Defaults
        if (col.constraints.defaultValue !== undefined) {
            if (col.constraints.defaultValue === 'NOW') {
                attributes.push('@default(now())');
            } else if (col.constraints.defaultValue === 'UUID') {
                attributes.push('@default(uuid())');
            } else if (col.constraints.defaultValue === 'CUID') {
                attributes.push('@default(cuid())');
            } else if (typeof col.constraints.defaultValue === 'string') {
                attributes.push(`@default("${col.constraints.defaultValue}")`);
            } else {
                attributes.push(`@default(${col.constraints.defaultValue})`);
            }
        }

        return `${col.name} ${type} ${attributes.join(' ')}`;
    }

    private generateRelations(table: Table): string {
        const lines: string[] = [];
        const indent = '  ';

        // 1. Outgoing Relations (This table has the FK)
        this.relationships
            .filter(r => r.fromTableId === table.id)
            .forEach(rel => {
                const toTable = this.tables.find(t => t.id === rel.toTableId);
                if (!toTable) return;

                const relationName = rel.name ? `"${rel.name}"` : `"${table.name}_${toTable.name}"`;

                let fkCol: Column | undefined;
                if (rel.fromColumnId) {
                    fkCol = table.columns.find(c => c.id === rel.fromColumnId);
                } else {
                    fkCol = table.columns.find(c => c.references?.tableId === rel.toTableId);
                }

                const pkCol = toTable.columns.find(c => c.constraints.isPk);
                const pkName = pkCol ? pkCol.name : 'id';

                if (fkCol) {
                    let actions = '';
                    if (rel.onDelete && rel.onDelete !== 'NO ACTION') actions += `, onDelete: ${this.mapAction(rel.onDelete)}`;
                    if (rel.onUpdate && rel.onUpdate !== 'NO ACTION') actions += `, onUpdate: ${this.mapAction(rel.onUpdate)}`;

                    const navFieldName = toTable.name.charAt(0).toLowerCase() + toTable.name.slice(1);
                    lines.push(`${navFieldName} ${toTable.name} @relation(name: ${relationName}, fields: [${fkCol.name}], references: [${pkName}]${actions})`);
                }
            });

        // 2. Incoming Relations (Other tables point to this one)
        this.relationships
            .filter(r => r.toTableId === table.id)
            .forEach(rel => {
                const fromTable = this.tables.find(t => t.id === rel.fromTableId);
                if (!fromTable) return;

                const relationName = rel.name ? `"${rel.name}"` : `"${fromTable.name}_${table.name}"`;

                let typeSuffix = '[]';
                if (rel.type === '1:1') {
                    typeSuffix = '?';
                }

                const navFieldName = fromTable.name.charAt(0).toLowerCase() + fromTable.name.slice(1);
                lines.push(`${navFieldName} ${fromTable.name}${typeSuffix} @relation(name: ${relationName})`);
            });

        return lines.map(l => indent + l).join('\n');
    }

    private generateStandardFields(table: Table): string {
        const lines: string[] = [];
        const indent = '  ';

        if (table.options?.timestamps) {
            lines.push('createdAt DateTime @default(now())');
            lines.push('updatedAt DateTime @updatedAt');
        }

        if (table.options?.softDelete) {
            lines.push('deletedAt DateTime?');
        }

        if (table.options?.multiTenant) {
            lines.push('tenantId String');
        }

        return lines.map(l => indent + l).join('\n');
    }

    private mapAction(action: string | undefined): string {
        if (!action) return 'NoAction';
        switch (action) {
            case 'CASCADE': return 'Cascade';
            case 'SET NULL': return 'SetNull';
            case 'RESTRICT': return 'Restrict';
            case 'NO ACTION': return 'NoAction';
            case 'SET DEFAULT': return 'SetDefault';
            default: return 'NoAction';
        }
    }
}
